/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "print_rpc.h"

bool_t
print_operation_1_svc(char *username, char *operation, char *date, char *hour, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	printf("%s %s %s %s\n", username, operation, date, hour);

	return retval;
}

int
printrpc_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
